name: 'Deploy Theme'
description: 'Zip & deploy a theme to your Ghost site'
inputs:
  api-url:
    description: 'Ghost Admin API Url'
    required: true
  api-key:
    description: 'Ghost Admin API Key'
    required: true
  exclude:
    description: 'Files or folders to exclude (space-separated list)'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
